import { Header } from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen grid grid-cols-1 grid-rows-[4rem_1fr_8rem] md:grid-rows-[6rem_1fr_8rem] bg-white">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
